<?php

/**
 * PluginaReusableSlideshowSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaReusableSlideshowSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaReusableSlideshowSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaReusableSlideshowSlot');
    }
}