<?php

/**
 * PluginaBetterTwitterSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaBetterTwitterSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaBetterTwitterSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaBetterTwitterSlot');
    }
}