<?php

/**
 * PluginaMapSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaMapSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaMapSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaMapSlot');
    }
}