<?php

/**
 * PluginaContactSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaContactSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaContactSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaContactSlot');
    }
}