<?php

/**
 * PluginaAnchorTitleSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaAnchorTitleSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaAnchorTitleSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaAnchorTitleSlot');
    }
}