<?php

/**
 * PluginaPollChoiceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaPollChoiceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaPollChoiceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaPollChoice');
    }
}