<?php

/**
 * PluginaEtsySlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaEtsySlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaEtsySlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaEtsySlot');
    }
}