<?php

/**
 * PluginaPollTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaPollTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaPollTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaPoll');
    }
}