<?php

/**
 * PluginaReusableSlideshowSlot
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginaReusableSlideshowSlot extends BaseaReusableSlideshowSlot
{
  /**
   * DOCUMENT ME
   * @return mixed
   */
  public function isOutlineEditable()
  {
    // We have an edit button and don't use an in-place editor
    return false;
  }

  /**
   * Returns the media items of the slot being reused, if any, otherwise
   * the media items of this slot
   */
  public function getOrderedMediaItems()
  {
    $values = $this->getArrayValue();
    if (isset($values['reuse']))
    {
      $slot = aReusableSlotTable::getReusedSlot($values['reuse']);
      if ($slot)
      {
        return $slot->getOrderedMediaItems();
      }
      else
      {
        return array();
      }
    }
    return parent::getOrderedMediaItems();
  }

  /**
   * DOCUMENT ME
   * @return mixed
   */
  public function getMediaItemOrder()
  {
    $data = $this->getArrayValue();
    if (isset($data['order']))
    {
      return $data['order'];
    }
    return null;
  }
}