<?php

/**
 * PluginaReusableSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaReusableSlotTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object PluginaReusableSlotTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginaReusableSlot');
  }
  
  public function findOneBySlot($page_id, $area_name, $permid)
  {
    return $this->createQuery('r')->where('r.page_id = ? AND r.area_name = ? AND r.permid = ?', array($page_id, $area_name, $permid))->fetchOne();
  }
}