<?php

/**
 * PluginaReusableSlideshowSlot
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginaReusableSlideshowSlot extends BaseaReusableSlideshowSlot
{
  /**
   * DOCUMENT ME
   * @return mixed
   */
  public function isOutlineEditable()
  {
    // We have an edit button and don't use an in-place editor
    return false;
  }

  /**
   * Returns the media items of the slot being reused, if any, otherwise
   * the media items of this slot
   */
  public function getOrderedMediaItems()
  {
    error_log("getOrderedMediaItems");
    $values = $this->getArrayValue();
    if (isset($values['reuse']))
    {
      // This isn't terrible but it could be more efficient if I used
      // array hydration. The trouble with that is that I have to walk the
      // results of that join which would be a lot easier if I refactored
      // some of the code for that purpose that lives in PluginaPageTable
      $q = aPageTable::queryWithSlot($values['reuse']['area_name']);
      $q->andWhere('p.id = ?', $values['reuse']['page_id']);
      $q->andWhere('avs.permid = ?', $values['reuse']['permid']);
      $page = $q->fetchOne();
      if (!$page)
      {
        return array();
      }
      $slots = $page->getSlotsByAreaName($values['reuse']['area_name']);
      if (!isset($slots[$values['reuse']['permid']]))
      {
        return array();
      }
      $slot = $slots[$values['reuse']['permid']];
      return $slot->getOrderedMediaItems();
    }
    return parent::getOrderedMediaItems();
  }

  /**
   * DOCUMENT ME
   * @return mixed
   */
  public function getMediaItemOrder()
  {
    $data = $this->getArrayValue();
    if (isset($data['order']))
    {
      return $data['order'];
    }
    return null;
  }
}