<?php

/**
 * PluginbetterTwitterSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginbetterTwitterSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginbetterTwitterSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginbetterTwitterSlot');
    }
}