<?php

/**
 * PluginaWufooFormSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaWufooFormSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaWufooFormSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaWufooFormSlot');
    }
}