<?php

/**
 * PluginaPhotoGridSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaPhotoGridSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaPhotoGridSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaPhotoGridSlot');
    }
}