<?php

/**
 * PluginaPaypalButtonSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaPaypalButtonSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaPaypalButtonSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaPaypalButtonSlot');
    }
}