<?php

/**
 * PluginaEmbedFormSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaEmbedFormSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaEmbedFormSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaEmbedFormSlot');
    }
}