<?php

/**
 * PluginaBlogSlideshowSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaBlogSlideshowSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaBlogSlideshowSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaBlogSlideshowSlot');
    }
}