<?php

/**
 * PluginaEcwidProductSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaEcwidProductSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaEcwidProductSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaEcwidProductSlot');
    }
}